### ISSUE TITLE
Shift-tab to scroll back up through the list

### ISSUE THREAD

**Issue by LukasDahl** [0x6563/InfinitySearch#1]
First of all: Very cool addon! I do have a feature request though.
Would it be possible to get shift-tab capability to scroll the other way, like alt-tab/alt-shift-tab in windows?

**Comment by 0x6563** [comment]
Yep 85f819ad0bdb319e65bdb064dfedfb3bc4fcd0a3 should add that functionality. I am just going to try and bundle a few more fixes and features before the next release.
